/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leveldb.sample;

import org.iq80.leveldb.*;
import static org.iq80.leveldb.impl.Iq80DBFactory.*;
import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Options options = new Options();
        options.createIfMissing(true);
        try (DB db = factory.open(new File("example"), options);) {
            db.put(bytes("Tampa"), bytes("rocks"));
            String value = asString(db.get(bytes("Tampa")));
            db.delete(bytes("Tampa"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("hello");
    }
}
